# Generated by Django 4.2.27 on 2026-01-28 12:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الطلب')),
                ('description', models.TextField(help_text='اشرح ما تريده بالتفصيل', verbose_name='تفاصيل ومتطلبات الطلب')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر المتفق عليه (ريال)')),
                ('delivery_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدة التسليم (بالأيام)')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم المتوقع')),
                ('status', models.CharField(choices=[('pending', 'في انتظار الموافقة'), ('accepted', 'مقبول'), ('in_progress', 'قيد التنفيذ'), ('delivered', 'تم التسليم'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('disputed', 'متنازع عليه')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('payment_status', models.CharField(choices=[('pending', 'في الانتظار'), ('paid', 'مدفوع'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_customer', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('provider', models.ForeignKey(limit_choices_to={'role': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_provider', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الخدمة')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order', verbose_name='الطلب')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة طلب',
                'verbose_name_plural': 'رسائل الطلبات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المرحلة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الإنجاز (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('order_index', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعالم',
                'ordering': ['order', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deliveries/%Y/%m/', verbose_name='ملف التسليم')),
                ('description', models.TextField(help_text='اشرح ما تم إنجازه', verbose_name='وصف التسليم')),
                ('delivered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='مقبول')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_note', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تسليم',
                'verbose_name_plural': 'التسليمات',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='orders_orde_custome_c9b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['provider', 'status'], name='orders_orde_provide_856163_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
    ]
