# Generated by Django 4.2.27 on 2026-01-28 11:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('role', models.CharField(choices=[('customer', 'عميل'), ('provider', 'مقدم خدمة'), ('admin', 'مدير')], default='customer', max_length=20, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يكون بصيغة: 05XXXXXXXX', regex='^(05|5)(5|0|3|6|4|9|1|8|7)([0-9]{7})$')], verbose_name='رقم الجوال')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='حساب موثق')),
                ('is_active', models.BooleanField(default=True, verbose_name='حساب نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='نبذة تعريفية')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='صورة الملف الشخصي')),
                ('specialization', models.CharField(blank=True, help_text='مثال: تصميم جرافيك، برمجة ويب، تسويق', max_length=100, verbose_name='التخصص')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='بالريال السعودي', max_digits=10, null=True, verbose_name='السعر بالساعة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='إجمالي الطلبات')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='الطلبات المكتملة')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='من 0 إلى 5', max_digits=3, verbose_name='متوسط التقييم')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح لطلبات جديدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف مقدم خدمة',
                'verbose_name_plural': 'ملفات مقدمي الخدمات',
                'ordering': ['-average_rating', '-completed_orders'],
            },
        ),
    ]
