# Generated by Django 5.2.10 on 2026-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='بالريال اليمني', max_digits=10, null=True, verbose_name='السعر بالساعة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال'),
        ),
    ]
