# Generated by Django 4.2.27 on 2026-03-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_providerprofile_hourly_rate_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الحساب'),
        ),
    ]
