# Generated by Django 4.2.27 on 2026-03-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_providerprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProviderProfile',
            fields=[
            ],
            options={
                'verbose_name': 'طلب اعتماد مقدم خدمة',
                'verbose_name_plural': 'طلبات الاعتماد المعلقة (مقدمي الخدمات)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.providerprofile',),
        ),
    ]
