# Generated by Django 4.2.30 on 2026-08-22 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_managedservice_qualification_specialization_and_more"),
        ("core", "0002_city_district_district_unique_district_per_city"),
        ("accounts", "0009_seed_provider_document_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerprofile",
            name="location_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provider_profiles",
                to="core.city",
                verbose_name="المدينة المختارة",
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="location_district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provider_profiles",
                to="core.district",
                verbose_name="المديرية المختارة",
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="qualification_choices",
            field=models.ManyToManyField(
                blank=True,
                related_name="providers",
                to="marketplace.qualification",
                verbose_name="المؤهلات المختارة",
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="specializations",
            field=models.ManyToManyField(
                blank=True,
                related_name="providers",
                to="marketplace.specialization",
                verbose_name="التخصصات",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.city",
                verbose_name="المدينة المختارة",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location_district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.district",
                verbose_name="المديرية المختارة",
            ),
        ),
        migrations.CreateModel(
            name="ProviderVerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "مقبول"),
                            ("rejected", "مرفوض"),
                            ("needs_documents", "يحتاج مستندات"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="ملاحظة الإدارة"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="accounts.providerprofile",
                    ),
                ),
                (
                    "requested_services",
                    models.ManyToManyField(
                        related_name="verification_requests",
                        to="marketplace.managedservice",
                        verbose_name="الخدمات المطلوبة",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب توثيق مقدم خدمة",
                "verbose_name_plural": "طلبات توثيق مقدمي الخدمات",
                "ordering": ["-created_at"],
            },
        ),
    ]
