# Generated by Django 4.2.30 on 2026-08-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_providerprofile_location_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerverificationrequest",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="verification_requests",
                to="accounts.providerdocument",
                verbose_name="المستندات",
            ),
        ),
        migrations.AddField(
            model_name="providerverificationrequest",
            name="profile_snapshot",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="لقطة بيانات التوثيق"
            ),
        ),
        migrations.AddField(
            model_name="providerverificationrequest",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ التقديم"
            ),
        ),
        migrations.AlterField(
            model_name="providerverificationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("approved", "مقبول"),
                    ("rejected", "مرفوض"),
                    ("needs_documents", "يحتاج مستندات"),
                    ("on_hold", "معلق"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
    ]
