# Generated by Django 4.2.27 on 2026-01-28 11:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='bi-tag', help_text='اسم أيقونة Bootstrap Icons (مثل: bi-laptop, bi-brush)', max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, help_text='الأرقام الأصغر تظهر أولاً', verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='marketplace.category', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخدمة')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(help_text='اشرح ما تقدمه في هذه الخدمة بالتفصيل', verbose_name='وصف الخدمة')),
                ('price_type', models.CharField(choices=[('fixed', 'سعر ثابت'), ('hourly', 'بالساعة'), ('negotiable', 'قابل للتفاوض')], default='fixed', max_length=20, verbose_name='نوع السعر')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='اترك فارغاً إذا كان قابل للتفاوض', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر (ريال)')),
                ('delivery_time', models.IntegerField(help_text='كم يوماً تحتاج لإنجاز هذه الخدمة؟', validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدة التسليم (بالأيام)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/%Y/%m/', verbose_name='صورة الخدمة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('paused', 'متوقف مؤقتاً'), ('closed', 'مغلق')], default='active', max_length=20, verbose_name='الحالة')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('orders_count', models.IntegerField(default=0, verbose_name='عدد الطلبات')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='متوسط التقييم')),
                ('is_featured', models.BooleanField(default=False, help_text='ستظهر في الصفحة الرئيسية', verbose_name='خدمة مميزة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='marketplace.category', verbose_name='التصنيف')),
                ('provider', models.ForeignKey(limit_choices_to={'role': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الخدمة')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='marketplace_status_204a90_idx'), models.Index(fields=['category', 'status'], name='marketplace_categor_e8a41c_idx'), models.Index(fields=['provider', 'status'], name='marketplace_provide_c7ef54_idx')],
            },
        ),
    ]
