# Generated by Django 4.2.27 on 2026-02-02 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('YER', 'ريال يمني'), ('SAR', 'ريال سعودي'), ('USD', 'دولار أمريكي')], default='YER', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اترك فارغاً إذا كان قابل للتفاوض', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر'),
        ),
    ]
