# Generated by Django 4.2.27 on 2026-03-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_service_currency_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('paused', 'متوقف مؤقتاً'), ('closed', 'مغلق')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
