# Generated by Django 4.2.27 on 2026-03-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
