# Generated by Django 4.2.27 on 2026-03-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_category_slug_remove_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingService',
            fields=[
            ],
            options={
                'verbose_name': 'خدمة معلقة للموافقة',
                'verbose_name_plural': 'الخدمات المعلقة للموافقة',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.service',),
        ),
    ]
