# Generated by Django 4.2.27 on 2026-03-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_pendingservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingService',
        ),
    ]
