# Generated by Django 4.2.30 on 2026-08-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_providerservice_category_image_category_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="الاسم"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
            ],
            options={
                "verbose_name": "خدمة أساسية",
                "verbose_name_plural": "الخدمات الأساسية",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="الاسم"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "مؤهل",
                "verbose_name_plural": "المؤهلات",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="الاسم"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تخصص مقدم خدمة",
                "verbose_name_plural": "تخصصات مقدمي الخدمات",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="providerservice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="providerservice",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("approved", "مقبولة"),
                    ("rejected", "مرفوضة"),
                    ("active", "نشطة"),
                    ("suspended", "موقوفة"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="providerservice",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_services",
                to="marketplace.service",
            ),
        ),
        migrations.AddField(
            model_name="managedservice",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_services",
                to="marketplace.category",
                verbose_name="التصنيف",
            ),
        ),
        migrations.AddField(
            model_name="providerservice",
            name="catalog_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_services",
                to="marketplace.managedservice",
                verbose_name="الخدمة الأساسية",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerservice",
            constraint=models.UniqueConstraint(condition=models.Q(("service__isnull", False)), fields=("provider", "service"), name="unique_provider_listing_service"),
        ),
        migrations.AddConstraint(
            model_name="providerservice",
            constraint=models.UniqueConstraint(condition=models.Q(("catalog_service__isnull", False)), fields=("provider", "catalog_service"), name="unique_provider_catalog_service"),
        ),
        migrations.AddIndex(
            model_name="managedservice",
            index=models.Index(
                fields=["category", "is_active", "order"],
                name="marketplace_categor_4785a5_idx",
            ),
        ),
    ]
