# Generated by Django 4.2.30 on 2026-08-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_managedservice_qualification_specialization_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="providerservice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("catalog_service__isnull", True), ("service__isnull", False)
                    ),
                    models.Q(
                        ("catalog_service__isnull", False), ("service__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="provider_service_exactly_one_source",
            ),
        ),
    ]
