# Generated by Django 4.2.30 on 2026-08-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_city_district_district_unique_district_per_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("provider_submitted", "Provider submitted"),
                    ("provider_verified", "Provider verified"),
                    ("provider_rejected", "Provider rejected"),
                    ("documents_requested", "Documents requested"),
                    ("new_order", "New order"),
                    ("order_accepted", "Order accepted"),
                    ("order_rejected", "Order rejected"),
                    ("payment_successful", "Payment successful"),
                    ("payment_failed", "Payment failed"),
                    ("order_started", "Order started"),
                    ("order_delivered", "Order delivered"),
                    ("order_completed", "Order completed"),
                    ("new_review", "New review"),
                    ("commission_accepted", "Commission accepted"),
                    ("payment_proof_uploaded", "Payment proof uploaded"),
                    ("account_status_changed", "Account status changed"),
                    ("admin_message", "Admin message"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
