# Generated by Django 4.2.30 on 2026-08-21 15:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_seed_provider_document_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("code", models.SlugField(unique=True)),
                ("color", models.CharField(default="#0d6efd", max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="commission_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="commission_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="proof_file",
            field=models.FileField(
                blank=True, null=True, upload_to="payment_proofs/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="proof_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_net_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_wallet_account_snapshot",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="payment",
            name="review_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(default="manual_wallet", max_length=80),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(default="manual_wallet", max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "في الانتظار"),
                    ("processing", "قيد المعالجة"),
                    ("under_review", "قيد مراجعة السند"),
                    ("paid", "مدفوع"),
                    ("failed", "فشل"),
                    ("rejected", "مرفوض"),
                    ("refunded", "مسترد"),
                    ("cancelled", "ملغي"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProviderWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الحساب يجب أن يحتوي على 6 إلى 20 رقمًا ويمكن أن يبدأ بـ +.",
                                regex="^\\+?[0-9]{6,20}$",
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_accounts",
                        to="accounts.providerprofile",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_accounts",
                        to="payments.wallet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.providerwallet",
            ),
        ),
        migrations.AddIndex(
            model_name="providerwallet",
            index=models.Index(
                fields=["provider", "is_active"], name="payments_pr_provide_9b9325_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerwallet",
            index=models.Index(
                fields=["wallet", "is_active"], name="payments_pr_wallet__7abe5f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="providerwallet",
            unique_together={("provider", "wallet")},
        ),
    ]
